### ISSUE TITLE
move resources under compute in pipeline interface?

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#170]
Originally raised in #54 

move the `resources:` subsection to be within `compute:` in a pipeline's interface.yaml file.

a pipeline_interface.yaml example:
```
compute:
    singularity_image: ${SIMAGES}a_pipeline
    docker_image: databio/a_pipeline
    resources:
        default:
            file_size: "0"
            cores: "8"
            mem: "16000"
            time: "0-04:00:00"
````
