### ISSUE TITLE
Allow (limited) specification of non-resource compute settings in project config

### ISSUE THREAD

**Issue by vreuter** [pepkit/looper#194]
Looperenv defines non-resource compute settings (cluster partition name + submission command & template). Provide users with the ability to specify (with key-value pair) one of these little bundles to use.

**Comment by nsheff** [comment]
Related to https://github.com/pepkit/looper/issues/235

I think this would be a special option in the `project.looper` section, whereby you could specify the compute package. This is essentially saying, in the `compute section, for point 1, "activated divvy compute package" -- how is the initial compute package chosen?

in priority order:

1. looper CLI option
2. if not specified, then use: project config option (`project.looper.compute_package` ?)
3. if not specified, use default divvy package.

**Comment by nsheff** [comment]
I believe it does *not* make sense to put this in the pipeline interface, which is pipeline-specific and not project/environment specific.

**Comment by stolarczyk** [comment]
> if not specified, then use: project config option (project.looper.compute_package ?)

what about `project.looper.compute.compute_package` or `project.looper.compute.package`?
The `project.looper.compute` section already exists for itemized resources specification:

for example:
```yaml
looper:
  output_dir: $HOME
  pipeline_interfaces: $CODE/bedstat/pipeline_interface_new.yaml
  compute:
    compute_package: local
    resources:
      cores: 100
```
