### ISSUE TITLE
Inconsistent or non-obvious compute_packages requirement

### ISSUE THREAD

**Issue by oddodaoddo** [pepkit/looper#218]
I have two "machines" - one is a FreeBSD box and the other is a Fedora VM running on it.
I have the following looper project file:
```
metadata:
    sample_annotation: ../lolacore.csv
    output_dir: output
    pipeline_interfaces: ../pipeline_interface.yaml
```

On the FreeBSD machine I can run things like
```
looper run --limit 5 project/pipeline_interface.yaml
```
If I run the same command on the Fedora VM, I get an exception:
```
Exception: Your config file is not in divvy config format (it lacks a compute_packages section).
```
I tried running this on the Fedora VM:
```
looper run --limit 5 --compute local project/pipeline_interface.yaml
```
to no avail.
