### ISSUE TITLE
Upgrading the pipeline interface to a template system

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#223]
Related to #7, #5, #38, #25 

Has arisen again with refgenie asset building: https://github.com/databio/databio_genomes/issues/5

The way we'd like to specify command-line args can't really be accommodated by the current pipeline interface system. It needs to move to something more powerful, such as a jinja2 template. this would enable us to really tailor the command issued.

So, the idea is: the pipeline interface would look something like:

```
protocol_mapping:
  "*": rsync

commands:
  rsync:
    name: rsync
    command: "rsync -av {{ sample.from }} {{ sample.to }}"
```

The refgenie problem would be solved like this:
```
    command: "refgenie build {% if sample.inputs %}--inputs \
{% for input in sample.inputs %}{{ input }} {% endfor % }{% endif %}"
```

and we could also allow accessing project-level attributes:

```
    command: "command... {{ project.attribute }}"
```
