### ISSUE TITLE
How should we define what a pipeline produces?

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#237]
Related to:  #32, #61, #94, #201, #216

# How should we define what a pipeline produces?

Originally the inputs were specified in the pipeline interface, now, we switched to a schema, which is used to validate a PEP for **input** into a pipeline. Here's an example: https://schema.databio.org/pipelines/pepatac.yaml

```
description: A PEP for ATAC-seq samples for the PEPATAC pipeline.
imports: http://schema.databio.org/pep/2.0.0.yaml
properties:
  samples:
    type: array
    items:
      type: object
      properties:
        sample_name: 
          type: string
          description: "Name of the sample"
        organism: 
          type: string
          description: "Organism"
        protocol: 
          type: string
          description: "Must be an ATAC-seq or DNAse-seq sample"
          enum: ["ATAC", "ATAC-SEQ", "ATAC-seq", "DNase", "DNase-seq"]
        genome:
          type: string
          description: "Refgenie genome registry identifier"
        read_type:
          type: string
          description: "Is this single or paired-end data?"
          enum: ["SINGLE", "PAIRED"]
        read1:
          anyOf:
            - type: string
              description: "Fastq file for read 1"
            - type: array
              items:
                type: string
        read2:
          anyOf:
            - type: string
              description: "Fastq file for read 2 (for paired-end experiments)"
            - type: array
              items:
                type: string
      required_input_attrs:
        - read1
      input_attrs:
        - read1
        - read2
      required:
        - sample_name
        - protocol
        - read1
        - genome
required:
  - samples
```

The schema is superior because it's decoupled from looper and can be used with `eido` now to validate the PEP. it's also reusable across pipelines.

So, what about **outputs** ? Right now the pipeline specifies what **outputs** it produces in the pipeline interface, like so:

```
pipelines:
  pepatac.py:
    name: PEPATAC
    path: pipelines/pepatac.py
    schema: https://schema.databio.org/pipelines/pepatac.yaml
    ...
    outputs:
      smooth_bw: "aligned_{sample.genome}/{sample.sample_name}_smooth.bw"
      exact_bw:  "aligned_{sample.genome}_exact/{sample.sample_name}_exact.bw"
      aligned_bam: "aligned_{sample.genome}/{sample.sample_name}_sort.bam"
```

This is very similar to what we used to do with required attributes for input. Is there therefore similar value in abstracting this concept out to a schema of some sort? What would it look like?

```
description: Sample objects produced by the PEPATAC pipeline.
properties:
  samples:
    type: array
    items:
      type: object
      properties:
        smooth_bw: 
          type: string
          description: "Smoothed bigwig output file"
          path: "aligned_{sample.genome}/{sample.sample_name}_smooth.bw"
```

Here, we extend the jsonschema vocabulary with a new term called 'path'. This **is not used to validate objects** at all, it's actually just used internally to **populate** them (which is our extension). It's exactly what we're already doing with `outputs`. So, what's the advantage of switching to a schema like this?

1. this schema could then *also* be used to validate the *output* of the pipeline, building on json-schema.
2. the input schema and output schema are parallel
3. it adds some self-documentation to what these items are, which would then be useful later, for example, in the looper summarize/perago output.
4. adds the possibility to have project-level outputs, not just sample-level outputs (which in fact I just realized is exactly the `summary_results` section)
5. we would refer to it with an external file, which decouples it from the pipeline interface, so it could in theory be re-used. -- this would also be satisfied by a simple file that listed outputs as key-value pairs.
6. (see below) it standardizes the outputs and summary results into one format

I'm not totally sold on this but want to throw it out there for comments.

Disadvantages:

1. it's more complex than a simple key-value pair for outputs
2. ~it only adds utility in the case of someone visualizing output with looper summarize/perago~ it adds utility for visualization, and also potentially for validating at a collate step.
3. requires some new tooling to realize the validation advantages, which is not yet entirely clear.

**Comment by nsheff** [comment]
The output schema could actually also subsume the `summary_results` section -- which has, in fact, almost reproduced everything in it:

from peppro:
```
    summary_results:
      - library_complexity_file:
        caption: "Library complexity file"
        description: "Plots each sample's library complexity on a single plot."
        thumbnail_path: "summary/{name}_libComplexity.png"
        path: "summary/{name}_libComplexity.pdf"
      - counts_table:
        caption: "Gene counts table"
        description: "Combines all sample gene count files into a project level gene counts table."
        thumbnail_path: "summary/{name}_countData.csv"
        path: "summary/{name}_countData.csv"
```

`caption` actually has an official term in jsonschema called `title`. So in an output schema this could look very similar:

```
description: Sample objects produced by the PEPATAC pipeline.
  properties:
    library_complexity_file:
      title: "Library complexity file"
      type: image (?)
      description: "Plots each sample's library complexity on a single plot."
      thumbnail_path: "summary/{name}_libComplexity.png"
      path: "summary/{name}_libComplexity.pdf"
    counts_table:
      title: "Gene counts table"
      type: string
      description: "Combines all sample gene count files into a project level gene counts table."
      thumbnail_path: "summary/{name}_countData.csv"
      path: "summary/{name}_countData.csv"
```

I think this would be a separate file from the outputs schema above. But it's interesting that we added these descriptive attributes here organically. Why wouldn't we also want these for the sample-level `outputs`? We should make them match.
