### ISSUE TITLE
New approach to pipeline_config.

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#257]
In the old pipeline interface we had this:

Occasionally, a particular project needs to run a particular flavor of a pipeline. 
Rather than creating an entirely new pipeline, you can parameterize the differences with a **pipeline config** file, 
It used to be that you could add a `pipeline_config` section in the **project config** file.

**Example**:

```yaml
pipeline_config:
  # pipeline configuration files used in project.
  # Key string must match the _name of the pipeline script_ (including extension)
  # Relative paths are relative to this project config file.
  # Default (null) means use the generic config for the pipeline.
  rrbs.py: null
  # Or you can point to a specific config to be used in this project:
  wgbs.py: wgbs_flavor1.yaml
```

This will instruct `looper` to pass `-C wgbs_flavor1.yaml` to any invocations of wgbs.py (for this project only). 
Your pipelines will need to understand the config file (which will happen automatically if you use pypiper).

## New approach

I think with the new way we can accomplish this in the command template for pipelines that obey this:

```
  command_template: >
    {% if project.looper.pipeline_config is defined %} -C {project.looper.pipeline_config}{% endif %}
```

does that make sense?

Similar to #256 we now lack the ability to point to particular pipelines, though.

**Comment by nsheff** [comment]
Ok I think both of these issues can basically be summarized by one question:

How should we modulate sample pipeline arguments using project attributes?

We need a general solution to this problem.

**Comment by nsheff** [comment]
one generic solution is:

include an 'extra' catch-all in the command template:

```
  command_template: >
    {pipeline.path} --args --blah --blah
    {% if sample.extra is defined %} {sample.extra}{% endif %}
```

Now, add whatever you want:

```
sample_modifiers:
  imply:
    - if:
        protocol: "rrbs"
      then:
        extra: "-C flavor.yaml --epilog"
```

This can handle both issues. Is it worth raising this approach to "recommended" status by:

- making the `{sample.extra}` appending to command-template automatic for all command templates
- adding a `looper.extra` section to pep config to accomplish the same thing at project level?

This would be accomplished by automatically appending this to every command_template within looper:

````
{% if sample.extra is defined %} {sample.extra}{% endif %}
{% if project.looper.extra is defined %} {project.looper.extra}{% endif %}
```

**Comment by nsheff** [comment]
this sounds a lot like the new `--pipeline-args`. Maybe these become the same thing, lumping all into one new section. I'd maybe call it `command_extra` or something. it's just allowing you to modulate the pipeline_args at CLI, project, or sample level.

pipeline_args is probably a bad name, since there are lots of other args... needs some idea of extra. also, 'command' is more universal.

**Comment by stolarczyk** [comment]
Ok, I like that we can portray it as a single concept. One question though, does the CLI extra args specification (`--command-extra`, old `--pipeline-args`) overwrite the config-sourced one or it just appends to the command?

**Comment by nsheff** [comment]
good question.  do we need `--command-extra` and `--command-extra-override` ?

**Comment by stolarczyk** [comment]
Yes, that's even better to give users the choice

So, the required changes to make it work are:

- [ ] change argument name: `--pipeline-args`  to `--command-extra`
- [ ] add `--command-extra-override` argument
- [ ] append the "extra" conditionals to every command template unless `--command-extra-override` is used
- [ ] document the approach

**Comment by nsheff** [comment]
I'm working on docs. should we use:

```
{% if sample.command_extra is defined %} {sample.command_extra}{% endif %}
{% if project.looper.command_extra is defined %} {project.looper.command_extra}{% endif %}
```

?

**Comment by nsheff** [comment]
is `--command-extra-override` a flag that modulates the behavior of `--comand-extra` ? or is it a separate argument that overrides?

**Comment by stolarczyk** [comment]
> is --command-extra-override a flag that modulates the behavior of --comand-extra ? or is it a separate argument that overrides?

I like the second option more. This is how I understood it when I first read it

For the extra attribute name, yes let's make it match the CLI argument

**Comment by nsheff** [comment]
## Project-level command extras

```
looper:
  command_extras: "--flavor"
```

## Sample-level command extras

You can use general PEP sample modifiers to add a `command_extras` attribute to any samples, however you wish. For example, if your extras are the same for all samples you could just use an `append` modifier:


```
sample_modifiers:
  append:
    command_extras: "--flavor-flag"
```

Or, if you need to modulate on the basis of some other attribute value, you could use an imply modifer:

```
sample_modifiers:
  imply:
    - if:
        protocol: "rrbs"
      then:
        command_extra: "-C flavor.yaml --epilog"
```

The *append* example is effectively the same as the project-level one.


So, should we axe the idea of project-level command-extras? Or, actually do these become relevant for a project pipeline? Are they added for a sample pipeline?
