### ISSUE TITLE
dynamic_variables_command_template needs a relative key

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#276]
If I want to include a python script in dynamic_variables_command_template, right now I have to either hard code the path in the pipeline interface, or execute looper from within a particular folder where that script exists.

Instead, this should operate the same with the `command_template` does, with some key specifying a path that's relative to the pipeline interface file.

**Comment by stolarczyk** [comment]
works this way:

```yaml
pipeline_name: refgenie
pipeline_type: sample
input_schema: refgenie_build.yaml
compute:
  dynamic_variables_script_path: build-compute-params.py # path, absolute or relative to the pipeline interface file
  dynamic_variables_command_template: >
    {pipeline.compute.dynamic_variables_script_path} -a {sample.asset}
...
```
