### ISSUE TITLE
adding an output explanation page to summarizer results

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#290]
@jpsmith5 wrote a glossary for pepatac output here: https://pepatac.databio.org/en/latest/glossary/

actually, it almost looks like the information in the output schema.

Could we put this info into the output schemas, and then display this information automatically in the looper summary page? what do you think?

-Nathan

**Comment by donaldcampbelljr** [comment]
Would this be a a static page created during the HTML Report generation that simply lists the output schema that was used to report the results?
Description would be the glossary definition?

```
pipeline_name: test_pipe
samples:
  collection_of_images:
    description: "This store collection of values or objects"
    type: array
    items:
      properties:
          prop1:
            description: "This is an example file"
            type: file
  output_file_in_object:
    type: object
    properties:
      prop1:
        description: "This is an example file"
        type: file
      prop2:
        description: "This is an example image"
        type: image
    description: "Object output"
  output_file:
    type: file
    description: "This a path to the output file"
  output_image:
    type: image
    description: "This a path to the output image"
project:
  another_collection_of_images:
    description: "This store collection of values or objects"
    type: array
    items:
      properties:
        prop1:
          description: "This is an example file"
          type: file
```
