### ISSUE TITLE
Is the new "paths" section a misnomer?

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#296]
## Should we rename the paths section?

we recently implemented a new section called `paths` that provides templates, which we are using to refer to either:
- paths to the main script
- paths to pre-submission hook scripts, which provides generic functionalty that supersedes the dynamic variables command templates.

In the process, we made it so these paths are *no longer automatically interpreted as relative*, so you have to say `{looper.output_dir}/blah` or something if you want to make the path relative to the piface or output dir. 

But now that they aren't automatically relatives, is `paths` the right name? Could you use this section for some other variable? Sure...it is actually now essentially mimicking the function of derived columns in peppy -- except more powerful and broad because it can draw not only from sample attributes, but from the other namespaces as well. 

So you could say,

```yaml
paths:
  pipeline_mode: {project.attr}-{sample.attr}
```

That would work -- but it's not a path. 

## Or is it needed at all?

In thinking about this, I realized that these are only used in the templates anyway; so maybe this section isn't even needed. for example, we now have this:

```yaml
paths:
  refgenie: "refgenie"
  compute_vars: "{looper.piface_dir}/build-compute-params.py"
pre_submit:
  command_template: >
    {pipeline.paths.compute_vars} -a {sample.asset} -g {sample.genome}
command_template: >
  {pipeline.paths.refgenie} build { sample.genome }/{ sample.asset }
```

but since we eliminated the relativity, you can also do:

```yaml
pre_submit:
  command_template: >
    {looper.piface_dir}/build-compute-params.py -a {sample.asset} -g {sample.genome}
command_template: >
  refgenie build { sample.genome }/{ sample.asset }
```
you're just building the commands right into the command templates, which also derive from namespaces.
