### ISSUE TITLE
make presubmit keys plural

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#297]
syntax should become:

```yaml
pre_submit:
  python_functions:
  command_templates:
```

functionality doesn't need to change.

_Originally posted by @nsheff in https://github.com/pepkit/looper/issues/285#issuecomment-694420899_
