### ISSUE TITLE
A new plugin for outputting all looper variable namespaces

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#298]
Related to #284 

- write a plugin function in looper that outputs the complete "submission" object, which contains all 5 namespaces
- that plugin function would have to define what variable it uses to determine where it writes its output

**Comment by xuebingjie1990** [comment]
here is how the output file looks for the hello-looper example:
```
project:
  pep_version: 2.0.0
  sample_table: /Users/bx2ur/Documents/SheffieldLab/hello_looper-master/project/sample_annotation.csv
  sample_modifiers:
    append:
      pipeline_interfaces: ../pipeline/pipeline_interface.yaml
  looper:
    output_dir: hello_looper_results
looper:
  pep_config: /Users/bx2ur/Documents/SheffieldLab/hello_looper-master/project/project_config.yaml
  results_subdir: hello_looper_results/results_pipeline
  submission_subdir: hello_looper_results/submission
  output_dir: hello_looper_results
  sample_output_folder: hello_looper_results/results_pipeline/frog_1
  job_name: count_lines_frog_1
  total_input_size: 0.0
  log_file: hello_looper_results/submission/count_lines_frog_1.log
  piface_dir: /Users/bx2ur/Documents/SheffieldLab/hello_looper-master/pipeline
pipeline:
  pipe_iface_file: /Users/bx2ur/Documents/SheffieldLab/hello_looper-master/pipeline/pipeline_interface.yaml
  source: /Users/bx2ur/Documents/SheffieldLab/hello_looper-master/pipeline/pipeline_interface.yaml
  pipeline_name: count_lines
  pipeline_type: sample
  path: /Users/bx2ur/Documents/SheffieldLab/hello_looper-master/pipeline/count_lines.sh
  pre_submit:
    python_functions:
    - looper.write_namespaces
  command_template: '{pipeline.path} {sample.file}'
compute:
  submission_template: /Users/bx2ur/.local/lib/python3.7/site-packages/divvy/default_config/divvy_templates/localhost_template.sub
  submission_command: sh
sample:
  sample_name: frog_1
  library: anySampleType
  file: data/frog1_data.txt
  pipeline_interfaces: ../pipeline/pipeline_interface.yaml
```
