### ISSUE TITLE
Pipeline interface needs to have a way to tell the summarizer what it produces

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#32]
Spin-off from #30 

How about adding a section like this to `pipeline_interface.yaml`:

```
    summary_results:
      "Alignment file": "summary/{project_name}.alignmentPercent.pdf"
      "Library size file": "summary/{project_name}.LibSize.pdf"
```

the idea is that there would be a few reserved keyword variables like `{project_name}` that would refer to project attributes, which may be used. or some other way of referring to items in the project config, since the files may want to be named with that information.

**Comment by nsheff** [comment]
New proposed format enables thumbnails and descriptions:
```
    summary_results:
      - alignment_file:
        caption: "Alignment file"
        description: "Plots alignment rates to all pre-alignments and primary genome."
        thumbnail_path: "summary/{name}.alignmentPercent.png"
        path: "summary/{name}.alignmentPercent.pdf"
      - lib_file:
        caption: "Library size file"
        thumbnail_path: "summary/{name}.LibSize.png"
        path: "summary/{name}.LibSize.pdf"
```
