### ISSUE TITLE
how to skip few samples for the run

### ISSUE THREAD

**Issue by arpanda** [pepkit/looper#324]
Hi,
Initially, I ran 10 samples using the below project setup.
```
looper:
  output_dir: /home/my_path
  cli:
    run:
      limit: 10
```
So for the next run, how can I skip those first 10 samples. can you please help. Thanks.
