### ISSUE TITLE
multiple bugs in writing sample yamls fails with custom path

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#329]
If specifying a custom path like 

```
pre_submit:
  python_functions:
  - looper.write_sample_yaml
var_templates:
  sample_yaml_path: "{looper.output_dir}/{sample.sample_name}.yaml"
```

it actually uses the *first* sample name to name to the file for subsequent samples... so it overwrites every sample yaml to `pipeline_results/sample1.yaml`

There's a number of bugs in the handling of custom yaml paths.
