### ISSUE TITLE
looper variable namespaces should be updated to contain what is in the `.looper` config file

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/looper#423]
Original comment: looper variable namespaces need to be updated; in particular, does the looper namespace get what's in the .looper config file now?

- [x] confirm that, with the recent changes to the looper config files, the namespace is being updated with the appropriate values.

**Comment by donaldcampbelljr** [comment]
**Some notes:**
-Looper reads the config file and sets _arguments_ based on the config file:
https://github.com/pepkit/looper/blob/6523e4b525570aa0f7b3013d19a049d1866a28df/looper/cli_looper.py#L593-L619

However, when Looper creates a Project, not all of these lines from the config file become attributes on the Project.

Specific example is with the addition of pipestat in the looper config file:
```
pep_config: ./project/project_config.yaml
output_dir: ./results
pipeline_interfaces:
  sample:  ./pipeline_pipestat/pipeline_interface.yaml
pipestat:
  results_file_path: results.yaml
```
The project does not contain the `results_file_path`. It does, however, contain a boolean `pipestat_configured = True`.

Further in the process, SubmissionConductor builds the looper namespace:
https://github.com/pepkit/looper/blob/6523e4b525570aa0f7b3013d19a049d1866a28df/looper/conductor.py#L462-L500

It appears that only select items are added to the Looper namespace. The config file that is added is the `project_config` NOT the `looper_config`.
