### ISSUE TITLE
Appending "command_extra" for looper runp appears to be broken

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/looper#475]
`test_cmd_extra_project` in `test_run.py`:

Appending "command_extra" args shows up in the submission scripts when using `looper run` but not when using `looper runp`

**Comment by donaldcampbelljr** [comment]
I believe this may have been opened in error. I cannot reproduce it, and the test seems to be working fine for both `run` and `runp` commands. Closing for now.

**Comment by donaldcampbelljr** [comment]
I found the broken test and realized that I was not modifying the project config in a way that the submission conductor was expecting. 

For project level (`runp` command):
```
name: looper_advanced_test
pep_version: 2.0.0
sample_table: annotation_sheet.csv
looper:
  command_extra: string
```

For sample levels (`run`command):

```
name: looper_advanced_test
pep_version: 2.0.0
sample_table: annotation_sheet.csv
sample_modifiers:
  append:
    command_extra: string
    attr: val
```

Leaving this as closed.
