### ISSUE TITLE
For Looper 2.0, we will consolidate sample and project level pipeline interfaces under a single interface.

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/looper#493]
For Looper 2.0, we will consolidate sample and project level pipeline interfaces under a single interface. This will break backwards compatibility.

```yaml
pipeline_name: example_pipestat_pipeline
output_schema: pipestat_output_schema.yaml
sample_interface:
  command_template: >
   python {looper.piface_dir}/count_lines.py {sample.file} {sample.sample_name} {pipestat.results_file}
project_interface:
  command_template: >
   python {looper.piface_dir}/count_lines_project.py {sample.file} {pipestat.results_file}
```

And the output schema pipeline name must match with the pipeline interface pipeline_name. We will enforce this by raising an exception of they do not match.

_Originally posted by @donaldcampbelljr in https://github.com/pepkit/looper/issues/492#issuecomment-2130108986_
