### ISSUE TITLE
looper can't handle pipelines with multiple position arguments

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#5]
see this pipeline interface:

```
pipelines:
  fetch:
    name: fetch
    path: "rsync -av"
    arguments:
      "": from
      "": to
```

Doesn't work, I believe because `from` and `to` have the same key. You can get around this with:

```
pipelines:
  fetch:
    name: fetch
    path: "rsync -av"
    arguments:
      "": from
      " ": to
```

but we should fix this eventually.
