### ISSUE TITLE
looper cli is not taking priority if cli modifiers are used in looper config

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/looper#518]
if i use looper with a limit command
`looper run --limit 2`

but then place this in my looper config:
```
pep_config: project/project_config.yaml
output_dir: "results"
pipeline_interfaces:
  - pipeline/pipeline_interface.yaml
cli:
  run:
    limit: 1
```

The config file takes priority but it _should_ be the other way around. The CLI should always take priority.
