### ISSUE TITLE
Enable the use of a project config file's custom compute section 

### ISSUE THREAD

**Issue by jpsmith5** [pepkit/looper#54]
Modify `Looper` to be able to to use an individual project's config file's custom settings for requested resources.  Also, move the `resources:` subsection to be within `compute:` in a pipeline's interface.yaml file.

a pipeline_interface.yaml example:
```
compute:
    singularity_image: ${SIMAGES}a_pipeline
    docker_image: databio/a_pipeline
    resources:
        default:
            file_size: "0"
            cores: "8"
            mem: "16000"
            time: "0-04:00:00"
````

a project config.yaml example:
```
resources:
    default:
        file_size: "0"
        cores: "8"
        mem: "16000"
        time: "0-04:00:00"
````
