### ISSUE TITLE
Cannot use pipestat flag_file_dir in a downstream pipeline submitted by looper

### ISSUE THREAD

**Issue by donaldcampbelljr** [pepkit/looper#548]
Basically, here is my looper config:

```
pep_config: metadata/pep_config.yaml
output_dir: ${RESULTS}
pipeline_interfaces:
  - pipeline/pipeline_interface.yaml
pipestat:
  pephub_path: donaldcampbelljr/human_seqcol_digests:default
  flag_file_dir: ${RESULTS}/flags
```

My pipeline interface:
```
pipeline_name: brickyard_refgenome_download
sample_interface:
  command_template: >
    python3 pipeline/refgenome_brickyard_download.py {sample.sample_name} {sample.ftp_file_path} {sample.species} {sample.common_genome_name} {sample.authority} {sample.file_type} {pipestat.pephub_path} {sample.download_location} {pipestat.flag_file_dir}

```

I see this error during sample submission:
```
Error populating command template: 'yacman.yacman_future.FutureYAMLConfigManager object' has no attribute 'flag_file_dir'
> Not submitted: 'yacman.yacman_future.FutureYAMLConfigManager object' has no attribute 'flag_file_dir'
```
