### ISSUE TITLE
toggling derived attributes in looper summarize results.

### ISSUE THREAD

**Issue by nsheff** [pepkit/looper#82]
It would be nice if the looper summary results page could toggle between showing derived attribute keys and actual derived attributes.

For any attributes listed as `derived_attributes`, the `Sample` object will have an additional attribute for the key. For example, if the attribute were `color`, it would be an attribute called `color_key`.

We could use this along with `CSS` to toggle which is displayed for that attribute, the key or the value.

**Comment by donaldcampbelljr** [comment]
We've moved reporting/summarize to Pipestat. Currently, in pipestat, it appears that we can modify a color attribute similar to what we do via a status schema:

```
running:
  description: "the pipeline is running"
  color: [30, 144, 255] # dodgerblue
completed:
  description: "the pipeline has completed"
  color: [50, 205, 50] # limegreen
```
Basically, should this now be done in the `output_schema`? And `pipestat summarize` can use that as a color entry in the reported table?

```
pipeline_name: default_pipeline_name
samples:
  number_of_things:
    type: integer
    description: "Number of things"
    color: [50, 205, 50] # limegreen
```
